FROM redis:5.0.14
#COPY redis.conf /etc/redis/redis.conf


#构建镜像
#docker build -t redis:5.0.14 .

#在终端里启动容器：
#docker run -p 6379:6379 --name redis_5_0_14 -d redis:5.0.14 --appendonly yes  --requirepass 123456
#redis-server /etc/redis/redis.conf 以配置文件启动redis，加载容器内的conf文件
#–appendonly yes 开启持久化
#--requirepass 123456 设置密码为123456