version: "3"
services:
   frontend:
      container_name: eval
      image: tomcat:7.0.109
      ports:
         - 9002:8080
      volumes:
         #- /mnt/docker/eval/tomcatconf:/usr/local/tomcat/conf
         - /mnt/docker/eval/www:/usr/local/tomcat/webapps
      restart: always
